---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: '{{ include "neurox-workload-agent.fullname" . }}'
  name: '{{ include "neurox-workload-agent.fullname" . }}'
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: 8000
  selector:
    app: '{{ include "neurox-workload-agent.fullname" . }}'
