{{- if .Values.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "5"
  name: '{{ include "neurox-workload.fullname" . }}-cleanup-job-hook'
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "5"
  name: '{{ include "neurox-workload.fullname" . }}-cleanup-job-hook'
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "roles"
    resourceNames:
      - '{{ include "neurox-workload.fullname" . }}-setup-job-hook'
    verbs:
      - "delete"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "rolebindings"
    resourceNames:
      - '{{ include "neurox-workload.fullname" . }}-setup-job-hook'
      - '{{ include "neurox-workload.fullname" . }}-cleanup-job-hook'
    verbs:
      - "delete"
  - apiGroups:
      - ""
    resources:
    {{- if .Values.prometheus.enabled }}
      - "configmaps"
    {{- end }}
      - "serviceaccounts"
    resourceNames:
      - '{{ include "neurox-workload.fullname" . }}-setup-job-hook'
    verbs:
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/hook-weight": "6"
  name: '{{ include "neurox-workload.fullname" . }}-cleanup-job-hook'
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "neurox-workload.fullname" . }}-cleanup-job-hook'
subjects:
  - kind: ServiceAccount
    name: '{{ include "neurox-workload.fullname" . }}-cleanup-job-hook'
{{- end }}
