---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "neurox-workload-agent.fullname" . }}'
  namespace: "{{ .Release.Namespace }}"
imagePullSecrets:
  - name: "{{ .Values.global.image.pullSecretName }}"
