---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: '{{ include "neurox-workload-agent.fullname" . }}'
spec:
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http
  jobLabel: app
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      app: '{{ include "neurox-workload-agent.fullname" . }}'
