---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "neurox-workload-manager.fullname" . }}'
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: '{{ include "neurox-workload-manager.fullname" . }}'
  template:
    metadata:
      labels:
        app: '{{ include "neurox-workload-manager.fullname" . }}'
        controlHostHash: '{{ (include "neurox-workload-manager.apiUrl" .) | sha256sum | trunc 10 }}'
        updated: '{{ now.Unix }}'
        version: "{{ .Chart.Version }}"
    spec:
    {{- if .Values.global.scheduling.affinity }}
      affinity: {{ toYaml .Values.global.scheduling.affinity | nindent 8 }}
    {{- end }}
      containers:
      - name: neurox-workload-manager
        image: '{{ include "neurox-workload-manager.image.registry" . }}:{{ default .Chart.AppVersion .Values.image.tag }}'
        imagePullPolicy: '{{ include "neurox-workload-manager.image.pullPolicy" . }}'
        env:
        - name: API_URL
          value: '{{ include "neurox-workload-manager.apiUrl" . }}'
        - name: CLUSTER_NAME
          value: "{{ .Values.global.workloadCluster.name }}"
        - name: CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: "{{ .Values.global.configmap.name }}"
              key: "{{ .Values.global.configmap.key }}"
        - name: FASTIFY_LOG_LEVEL
          value: '{{ .Values.global.log.level }}'
        - name: FASTIFY_LOG_REQUESTS
          value: '{{ .Values.global.log.requests }}'
        - name: FASTIFY_PRETTY_LOGS
          value: '{{ .Values.global.log.pretty }}'
        - name: FASTIFY_PORT
          value: '4080'
      {{- if .Values.global.workloadCluster.local }}
        - name: LOCAL_CLUSTER
          value: 'true'
      {{- end }}
        - name: NODE_ENV
          value: "{{ .Values.global.nodeEnv }}"
        - name: RELEASE_NAME
          value: '{{ .Release.Name }}'
        - name: RELEASE_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: SHARED_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.secret.name }}"
              key: "{{ .Values.secret.key }}"
        - name: WORKLOAD_CHART_VERSION
          valueFrom:
            configMapKeyRef:
              name: '{{ include "neurox-workload-manager.chartConfigMap.name" . }}'
              key: "{{ .Values.global.chartConfigMap.workloadKeys.version }}"
        - name: WORKLOAD_NAMESPACES
          value: '{{ join "," .Values.workloadNamespaces }}'
        ports:
        - containerPort: 4080
          name: http
    {{- if .Values.global.scheduling.nodeSelector }}
      nodeSelector: {{ toYaml .Values.global.scheduling.nodeSelector | nindent 8 }}
    {{- end }}
      serviceAccountName: '{{ include "neurox-workload-manager.fullname" . }}'
    {{- if .Values.global.scheduling.tolerations }}
      tolerations: {{ toYaml .Values.global.scheduling.tolerations | nindent 8 }}
    {{- end }}
