---
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "neurox-workload-manager.fullname" . }}'
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: '{{ include "neurox-workload-manager.fullname" . }}'
  type: ClusterIP
